### ISSUE TITLE
50 Smartest Companies

### ISSUE THREAD

**Issue by xuliker** [xuliker/my-kernel-dev-environment#104]
144	158	英特尔公司（INTEL)	59,387	10,316	美国

83	129	华为投资控股有限公司（HUAWEI INVESTMENT & HOLDING)	78,510.8	5,579.4	中国

* 利润
  * 苹果
  * 各种银行
  * 摩根
  * 伯克希尔公司
  * Alphabet
  * 三星
  * 丰田
  * 微软
  * 强生
  * 俄罗斯天然气
  * 沃尔玛
  * 软银
  * 威瑞森电信
  * AT&T
  * 房利美
  * IBM
  * 思科
  * 宝洁
  * 英特尔
  * 台积电
  * facebook

# 英特尔眼中的华为(转载)

　　英特尔内部有个特别的团队。“对华为来说，它代表了英特尔公司；对英特尔来说，它又代表了华为。”英特尔公司华为全球业务总监方粤生描述说。现在，除了传统电脑业务，这个团队的业务范围几乎涉猎两家公司的所有ICT产品技术。
　　有人问英特尔全球副总裁兼中国区总裁杨叙，英特尔和华为的合作有什么特点，他回答说：“华为和英特尔都是在以产品、技术创立的文化中不断发展，双方在方向上是一致的。”
　　现在，双方都受到ICT产业中最大的潮流——IT（信息技术）和CT（通信技术）融合的影响。在这个融合大潮中，英特尔强调对计算技术的创新，因为融合需要更强的计算力。而华为则于2011年做出重大决策——调整公司业务架构，设立运营商网络、企业业务和消费者业务3大部门，开拓运营商市场之外的新蓝海。
　　在过去10多年中，双方的合作从最初的通信领域扩展到服务器、存储和网络。现在，双方把共同的目标放在了未来云计算和大数据的机会上。
　　“中国技术生态系统”
　　很多人不会想到，10多年前，除了通信设备外，华为也开始与英特尔探讨服务器业务的合作。当时在英特尔服务器事业部的方粤生曾和来自公司亚太区及美国总部的同事，在华为做调研，这段经历令他记忆犹新。“我们当时得出的结论是，这家公司的技术相当厉害，在整个亚洲数一数二。”方粤生回忆说，“其实华为看得很远，当时已经看到若干年后，通用计算领域的许多产品和技术，将和传统网络和通信技术融合，于是开始做产品、技术和人才上的积累。”
　　在之后的10多年间，华为服务器业务有积累，也有挫折，经历了起起伏伏，直到两年多前企业业务BG成立之后，服务器才变成“大张旗鼓、全面铺开的业务”。在这个过程中，英特尔和华为的合作关系也发生了质的变化。
　　作为见证者之一，方粤生体会到，伙伴之间的合作深度能达到什么程度，取决于“出招人”和“接招人”匹配的能力。7年前，方粤生与国际、国内服务器厂商都打过交道。“那时，美国那些服务器企业与你谈论的，是很高深的芯片和主板设计技术；但国内企业和你谈论的，还主要集中在系统层面，像散热、电源管理、整机尺寸等等”。但在最近几年，这一状况正在发生变化。像华为，它与英特尔的合作已经深入到芯片层级。
　　最近英特尔在讨论一个新的概念——中国技术生态系统，这个生态系统原本考虑比较多的是平板和手机领域，方粤生说，其实还可以有网络和服务器生态系统，本地企业已经在很多方面进入全球领先状态。
　　全球战略合作
　　英特尔和华为合作深度的提升也体现在企业的战略层面。去年，在华为云计算大会（HCC）期间，英特尔和华为共同签署合作协议，建立IT产品与解决方案的全球战略合作关系。
　　“大家看到的合作只是冰山一角。”方粤生说，“它源自后台每天都在发生的产品和技术合作。”
　　方粤生认为，目前双方在服务器上已取得阶段性胜利。4路、8路服务器已经推出，16路和32路服务器还在研发当中，当然也是“采用了下一代甚至更前沿的技术”。
　　在去年HCC期间华为发布的FusionCube一体机，在一个半米高的空间内，把计算、存储、网络都融合到一个机框中。在一体机的研发过程中，双方除了硬件的合作外，英特尔还为华为推出的开源云操作系统FusionSphere提供技术上的帮助。
　　软件定义网络SDN是当前网络业界的一大热点。“华为在SDN和NSV（网络功能虚拟化）方面业界领先。”方粤生说，“我们与他们在这方面的碰撞和交流很有意义。”在国内电信运营商以及沃达丰等海外电信运营商的SDN项目中，英特尔作为第三方，与运营商和华为都展开合作。华为SDN的软硬件开发，借助了英特尔DPDK等工具和一些硬件平台。
　　在华为目前正布局的高性能计算市场，也借助了英特尔相关软硬件工具。“在今年HCC大会上将有相关产品发布。这是华为介入的新市场。”方粤生透露说。
　　现在，双方的互动很频繁。EVP（执行副总裁）对EVP、架构师对架构师、设计师对设计师，各层次的沟通很多。不久之前，双方管理层刚就未来客户端到底是用平板还是超级本，应用场景和所需的软件做了一次交流。“除了大家看到的合作，背后的交流和碰撞，有非常高的价值。”方粤生说。
　　华为3大特色
　　在与华为频繁的合作中，方粤生总结出令他印象深刻的华为3大特色——技术能力强、苦干精神和进取文化。
　　“我观察到，华为的技术人才很多，水平很高。”方粤生说，“华为能把这么多能人聚集在一起，非常不容易。”华为人的苦干精神也令人印象深刻。方粤生有时到华为深圳总部开会，晚上六七点，他和华为的合作伙伴走出办公室去食堂，起初，眼前的景象会把他吓一跳。“滚滚人流，都工作到那个时间，都去吃饭，饭后还有很多人回来继续工作。”他说，“在硅谷，我也见识过晚上许多公司有人加班的情况，但不会有那么多人。想想看，今天华为能取得成就，是有道理的。”
　　很多书籍和报道都曾提到华为的“狼性文化”，英特尔对此的描述是“Aggressive”，意思是进取心。“无论是产品研发还是前端市场，华为都不轻言放弃。他们一定要找到一种方法和机会，把这事做成，这让我感受很深。”方粤生说。
　　面向未来的项目合作
　　不过，华为在企业级市场还需要时间。
　　华为过往20年的经验，都是如何面对运营商或者互联网巨头那样超大型的直销客户，如何快速提供定制化解决方案。但企业市场，充斥着各种量级的客户。方粤生形容，华为原来面对的状况是，一个大客户买5000台设备，但现在，则是1000个客户，每个买5台设备。
　　“你怎么面对这1000个客户，做出适合他们的产品，怎么与分销、集成合作伙伴合作，这些，华为还需要时间。”他说。
　　不久之前，方粤生与英特尔欧洲同事探讨，在欧洲怎么帮助华为推广市场。“那里，华为还要面临更多困难，像语言、文化上的差异。但我相信，华为一定能做成”。
　　现在，英特尔和华为正在展开面向未来3年的项目合作。“我们今天与华为有很多具体项目，像微服务器、模块化的计算中心等，为两年后的市场需求共同打造一些东西”。在软件方面，英特尔还在与华为一起，夯实华为的一些解决方案，如开源云操作系统、存储解决方案等。

**Comment by UvpStar** [comment]
我们相信自己是一家领军型企业，是唯一一家可以为这个新兴的智能连接世界的每个细分市场——从云端到网络，再到边缘设备，提供支持的企业。

**Comment by liker12134** [comment]
http://tech.163.com/10/0816/14/6E7E6UCS00094IM3.html

**Comment by liker12134** [comment]
https://www.technologyreview.com/lists/companies/2017/

**Nvidia：新芯片**

**Amazon：亚马逊**

**Alphabet：谷歌母公司**

**Tencent：腾讯**

**Intel 英特尔**

**Apple 苹果公司**

**Facebook 脸书**

**Udacity 优达学城**

**Microsoft 微软**

**Rigetti Computing 量子计算技术公司**

**Salesforce 客户关系管理(CRM)软件服务提供商**

**Snap 内容提供**

**Ant Financial 蚂蚁金服**

**Baidu 百度**

**Alibaba 阿里巴巴**

**IBM** 

SpaceX：美国太空探索技术公司

23andMe：DNA鉴定公司

iFlytek：科大讯飞

Kite Pharma：凯德药业

Regeneron：美国再生元制药公司

Spark Therapeutics：火花基因疗法公司

Face ++ 旷视科技

First Solar  福斯第一太阳能

Quanergy Systems 自动驾驶激光雷达

Vestas Wind Systems 维斯塔斯风力技术

Merck 德国默克集团

Carbon 3D打印

Desktop Metal 美国桌面金属公司

Ionis Pharmaceuticals RNA靶标药物

Gamalon 机器学习

Illumina 遗传变异和生物学

DJI 大疆 

MercadoLibre 拉美地区最大的电商平台

Kindred AI 可穿戴设备

Sophia Genetics 基因治疗公司

Tesla 特斯拉

Oxford Nanopore DNA技术

Foxconn 富士康，自动化工厂

M-KOPA 供电系统

ForAllSecure 网络设备漏洞发现

Flipkart 印度电商公司弗利普卡特

Bluebird Bio 蓝鸟生物公司

Adidas 阿迪达斯

General Electric 通用电气

HTC 虚拟现实系统

Blueprism 机器人自动化软件

Africa Internet Group  非洲互联网集团

Veritas Genetics 奕真生物

Daimler 戴姆勒，电动卡车
